In [2]:
import numpy as np

docs = ['Well done!','Good work','Great effort','nice work','Excellent!','Weak','Poor effort!','not good','poor work','Could have done better.']
# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
# integer encode the documents
from keras.preprocessing.text import one_hot

vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[45, 28], [9, 20], [40, 2], [7, 20], [4], [11], [3, 2], [13, 9], [3, 20], [5, 39, 28, 47]]


In [9]:
# pad documents to a max length of 4 words
from keras.preprocessing.sequence import pad_sequences

max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[45 28  0  0]
 [ 9 20  0  0]
 [40  2  0  0]
 [ 7 20  0  0]
 [ 4  0  0  0]
 [11  0  0  0]
 [ 3  2  0  0]
 [13  9  0  0]
 [ 3 20  0  0]
 [ 5 39 28 47]]


In [10]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding


# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [11]:
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 80.000001


In [ ]:
# Use pre - trained word embeddings: GlOve and word2vec
# Link: https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/